version: "3"

services:

  hbase:
    image: hbase
    container_name: hbase
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
      - 46495:46495
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:9864"
    env_file:
      - ./hbase.env

volumes:
  hbase_data:
  hbase_zookeeper_data:

networks:
  docker-hadoop_default:
    external: true